INSERT INTO APP_DISCOUNT_TELCO.SERVICES 
(ID_SERVICE, SERVICE_NAME, PRICE, INCORPORATION_DATE, STATUS) 
VALUES(SEQ_ID_SERVICE.NEXTVAL, 'Telefonía', 20000, CURRENT_TIMESTAMP, 'activo');

INSERT INTO APP_DISCOUNT_TELCO.SERVICES 
(ID_SERVICE, SERVICE_NAME, PRICE, INCORPORATION_DATE, STATUS) 
VALUES(SEQ_ID_SERVICE.NEXTVAL, 'Cable', 30000, CURRENT_TIMESTAMP, 'activo');

INSERT INTO APP_DISCOUNT_TELCO.SERVICES 
(ID_SERVICE, SERVICE_NAME, PRICE, INCORPORATION_DATE, STATUS) 
VALUES(SEQ_ID_SERVICE.NEXTVAL, 'Plan de datos móviles', 35000, CURRENT_TIMESTAMP, 'activo');

INSERT INTO APP_DISCOUNT_TELCO.SERVICES 
(ID_SERVICE, SERVICE_NAME, PRICE, INCORPORATION_DATE, STATUS) 
VALUES(SEQ_ID_SERVICE.NEXTVAL, 'Plan Internet fijo', 90000, CURRENT_TIMESTAMP, 'activo');


